### ISSUE TITLE
Not compatible with GitHub File Icons

### ISSUE THREAD

**Issue by blackcater** [ovity/octotree#660] opened 2019-04-15 08:21 UTC
### Description

I have installed [Github File Icons](https://chrome.google.com/webstore/detail/github-file-icons/kkokonbjllgdmblmbichgkkikhlcnekp) and [Octotree](https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc) in my browser.

[Octotree](https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc) conflicts with [Github File Icons](https://chrome.google.com/webstore/detail/github-file-icons/kkokonbjllgdmblmbichgkkikhlcnekp).

### Environment (if bug)

* Octotree version: v3
* Browser & version: Chrome 73
* OS & version: MacOS 10.14.4
* Screenshot, if any (drag an image here)

![image](https://user-images.githubusercontent.com/9465551/56116978-b2729700-5f99-11e9-8cbd-010d2faf78df.png)

![image](https://user-images.githubusercontent.com/9465551/56117324-6d029980-5f9a-11e9-871e-96ca3014673e.png)

* Console error log below this line

**Comment by jdreesen** [comment] 2019-04-15 08:33
Duplicate of #650

**Comment by blackcater** [comment] 2019-04-15 08:37
@jdreesen I got it. :)

**Comment by buunguyen** [comment] 2019-04-15 14:31
Close as duplicated. Thanks for reporting.

**Closed by buunguyen** 2019-04-15 14:31 UTC
