### ISSUE TITLE
"Error: Private Repository" on non-master branches

### ISSUE THREAD

**Issue by coraWhite** [ovity/octotree#559] opened 2018-10-23 15:34 UTC
### Description
Octotree sidebar reports "Error: Private Repository" prompting to create a new access token on any branch for a Private Repository besides Master branch. Works normally on a Master branch. 

This started the day I updated Octotree to 2.5.0 and before Firefox was updated to 63.0. After updating Firefox to 63.0, same error.

I deleted previous access tokens and re-created a new one with no luck.

### Environment (if bug)

* Octotree version:  2.5.0
* Browser & version: Firefox 63.0 
* OS & version: Mac OSX 10.13.6

**Comment by leonard-waters** [comment] 2018-10-24 14:05
Same error occurring on Chrome as well.

- Octotree Version: 2.5.0
- Browser & Version: Chrome 69.0.3497.100
- OS & Version: Mac OSX 10.14.1

**Comment by duylam** [comment] 2018-10-24 15:53
@leonard-waters

> Took a quick look at this and it looks like the issue involves the request to Get a tree recursively. Only the first part of the branch name is being added to the query.

Thanks for the hint, it's correct that the mishandling branch name is the problem. The fixing code would be at https://github.com/ovity/octotree/blob/master/src/adapters/github.js#L124, I will explore more cases on url and apply a fix

**Comment by buunguyen** [comment] 2018-10-31 01:33
Fixed in 2.5.1.

**Closed by buunguyen** 2018-10-31 01:33 UTC

**Comment by leonard-waters** [comment] 2019-01-10 16:35
Similar error again, but not exactly the same. Naming convention does not seem to be related in this case.

**Comment by coraWhite** [comment] 2019-01-10 18:02
This issue has reoccurred for me as well, with versions:
Octotree: 2.5.1
Firefox: 64.0.2 (64-bit)
MacOS Mojave: 10.14.2

And the naming convention seems to be a consistent issue for me particularly. A non-master branch, such as `user` on a private repo will load correctly. However, a non-master branch containing `-`, `/`, or `_` does not load correctly on the same private repo.

**Comment by philmayfield** [comment] 2019-01-16 22:41
Octotree: 2.5.1
Chrome: 71.0.3578.98
MacOS Mojave: 10.14.2

I'm getting a similar error around naming of branches.  Branches with only characters appear to work fine with Octotree.  When using the `-` and `_` characters is where I'm seeing the error.  I tried for a bit to come up with a rhyme or reason, but best I can figure is its some combination of length and those special characters that is throwing it.  Very short branch names with them work ok, but longer names do not.

**Comment by llrs** [comment] 2019-01-21 14:10
I confirm that after renaming the branch (without "_" on my case) the issue is solved and the files are shown

**Comment by andersrehn** [comment] 2020-06-26 12:03
I'm getting error when using the `/` sign on branches `-` are fine.

**Comment by buunguyen** [comment] 2020-07-01 20:26
@andersrehn  thanks. GH just changed their DOM thus causes this error. Fixed in 5.2.1.
