### ISSUE TITLE
Getting "Forbidden" for some repos

### ISSUE THREAD

**Issue by RussKie** [ovity/octotree#1053] opened 2021-01-25 05:46 UTC
### Description

A number of Microsoft repos are now protected with an SSO, and it looks like this cripples Octotree, making it show "Forbidden". 
At the same time I can browse repos without issues (both logged in and logged out). 

I have re-generated PAT, and authorised it for SSO, but that doesn't appear to have any effect.
![image](https://user-images.githubusercontent.com/4403806/105665484-4cb38d00-5f2b-11eb-8c86-56c60ec7b20a.png)

### Repro steps:

1. Open https://github.com/MicrosoftDocs/test-bbtm-update in a incognito mode:
![octotree1](https://user-images.githubusercontent.com/4403806/105664953-07429000-5f2a-11eb-9e6f-6867e2715e81.gif)
2. In the console there're 2 errors while hitting these links:
![image](https://user-images.githubusercontent.com/4403806/105665035-322ce400-5f2a-11eb-9ed1-f68c9b5c7d05.png)
    * https://github.com/MicrosoftDocs/test-bbtm-update/security/overall-count
    * https://api.github.com/repos/MicrosoftDocs/test-bbtm-update/git/trees/main?recursive=1 (no idea why, it opens without any fuss)
3. Clicking the first link opens this page:
![image](https://user-images.githubusercontent.com/4403806/105665084-4f61b280-5f2a-11eb-8625-1117ea797db2.png)
4. I go through the challenge, and authenticate.
5. Refresh, and Octotree is still unable to retrieve the data.
In the console the second issue remains though: 
![image](https://user-images.githubusercontent.com/4403806/105665970-483ba400-5f2c-11eb-8e01-ba0d4ad633b0.png)

### Environment (if bug)

* Octotree version: 6.2.6
* Browser & version: Microsoft Edge 88.0.705.50 (Official build) (64-bit)
* OS & version: W10

**Comment by endyquang** [comment] 2021-01-31 07:03
Hi, I can’t reproduce. I can open that repo just fine in incognito mode, with or without access token. Instead of using token, can you try remove the token in the Octotree setting screen and authenticate with GitHub instead? Any tip to help me reproduce the issue would be much appreciated. Thanks.

**Comment by RussKie** [comment] 2021-02-04 23:48
Yeah, the issue isn't straight forward.

If I'm not logged in everything appears to work:
![image](https://user-images.githubusercontent.com/4403806/106968586-43cd8180-679d-11eb-8bd0-02f13597c4c0.png)

Logging in Octotree, it logs me in GitHub as well, and I get "Forbidden" error:
![image](https://user-images.githubusercontent.com/4403806/106968799-af175380-679d-11eb-8fef-39efeb1fe78e.png)

I can sign out from GitHub but remain signed in Octotree, and the issue remains.

I can speculate that the SSO interferes during the login, and _only_ when it knows I'm part of the org; hence it poses not issues for anonymous scenarios.



<details>
<summary>Could this be the error from Octotree?</summary>



![image](https://user-images.githubusercontent.com/4403806/106969325-bb4fe080-679e-11eb-8e05-9a37bc9cedf6.png)

```
content.js:formatted:16067 GET https://api.github.com/repos/MicrosoftDocs/test-bbtm-update/git/trees/main?recursive=1 403
xhr @ content.js:formatted:16067
async function (async)
xhr @ content.js:formatted:16061
getTree @ content.js:formatted:16021
loadCodeTree @ content.js:formatted:15879
_adapter.loadCodeTree @ content.js:formatted:17347
async function (async)
_adapter.loadCodeTree @ content.js:formatted:17334
_loadData @ content.js:formatted:13166
async function (async)
_loadData @ content.js:formatted:13161
(anonymous) @ content.js:formatted:13065
P @ content.js:formatted:12185
_searchOrLoadData @ content.js:formatted:13059
$jstree.settings.core.data @ content.js:formatted:13046
_load_node @ content.js:formatted:7549
load_node @ content.js:formatted:7489
refresh @ content.js:formatted:8779
show @ content.js:formatted:13056
e @ content.js:formatted:17857
async function (async)
e @ content.js:formatted:17842
o @ content.js:formatted:17927
i @ content.js:formatted:17901
async function (async)
i @ content.js:formatted:17901
e @ content.js:formatted:17859
async function (async)
e @ content.js:formatted:17842
ii @ content.js:formatted:17813
async function (async)
ii @ content.js:formatted:17699
(anonymous) @ content.js:formatted:18002
P @ content.js:formatted:12185
(anonymous) @ content.js:formatted:18002
async function (async)
(anonymous) @ content.js:formatted:18001
V @ content.js:formatted:12241
(anonymous) @ content.js:formatted:17999
c @ content.js:formatted:2685
d @ content.js:formatted:2696
setTimeout (async)
(anonymous) @ content.js:formatted:2706
l @ content.js:formatted:2578
fireWith @ content.js:formatted:2631
fire @ content.js:formatted:2635
l @ content.js:formatted:2578
fireWith @ content.js:formatted:2631
ready @ content.js:formatted:2787
q @ content.js:formatted:2772
```


</details>

**Comment by chasdevs** [comment] 2021-02-18 13:08
Seeing similar behavior.

**Comment by buunguyen** [comment] 2021-02-18 18:04
@RussKie I think you need to set the SSO-enabled PAT to the textbox with the placeholder "Or enter access token". Can you try it?

**Comment by RussKie** [comment] 2021-02-22 23:44
I generated a new token (clicking on the key icon), and enabled SSO:
![image](https://user-images.githubusercontent.com/4403806/108784528-b45d0680-75c3-11eb-98d1-16f2691692c5.png)
![image](https://user-images.githubusercontent.com/4403806/108784562-ca6ac700-75c3-11eb-9943-cf1f37a429c5.png)

Still I don't seem to be able to see the tree for https://github.com/MicrosoftDocs/sdk-api repo
![image](https://user-images.githubusercontent.com/4403806/108784676-07cf5480-75c4-11eb-8cee-dac75c175220.png)


Is there a (easy) way to debug this?

**Comment by buunguyen** [comment] 2021-02-23 00:52
@RussKie I see you generated the token. But did you copy and paste that token into the settings screen of Octotree? You can debug by open the dev console, looking at the HTTP request made by Octotree to GitHub and check if it includes the right token in the auth header.

**Comment by RussKie** [comment] 2021-02-23 00:54
Yes, I copied in :) But thanks for checking 👍 
I'm not big on the web stuff, but I'll try to work out how to check the auth header.

**Comment by buunguyen** [comment] 2021-02-23 22:11
@RussKie thanks, would be great if you can check. If the right token (the one with SSO enabled) is used in the request by Octotree, I don't see why it wouldn't work. But none of us has SSO to test so there maybe things we aren't aware of.

**Comment by RussKie** [comment] 2021-02-24 01:32
I'm pretty busy for the next week or so, and I'll report back when get more info.

**Comment by sadokx** [comment] 2021-08-31 18:28
I'm getting Forbidden on a private repo. Any idea why?

![image](https://user-images.githubusercontent.com/12555077/131556521-10e7d8e8-6dac-412f-a0ee-a37b0f2d11b7.png)

**Comment by endyquang** [comment] 2021-08-31 18:34
@sadokx If that is a repo of an origanization with [OAuth App access restrictions](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/about-oauth-app-access-restrictions), you need to manually request organizational approval for Octotree
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps

**Comment by sadokx** [comment] 2021-08-31 19:13
Thank you @endyquang !

**Comment by buunguyen** [comment] 2021-08-31 19:50
Thanks @endyquang and @sadokx. I'm closing this issue now. If it still happens, please let me know.

**Closed by buunguyen** 2021-08-31 19:50 UTC

**Comment by saltchess** [comment] 2022-11-23 18:35
> @sadokx If that is a repo of an origanization with [OAuth App access restrictions](https://docs.github.com/en/organizations/restricting-access-to-your-organizations-data/about-oauth-app-access-restrictions), you need to manually request organizational approval for Octotree https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-your-membership-in-organizations/requesting-organization-approval-for-oauth-apps

Now there's a problem that I'm forbidden by private repo created by myself in my organization, with raw settings ("Integration access requests" radio selected). I wonder what the problem is.
