### ISSUE TITLE
Contents not displayed for branches containing forward slash

### ISSUE THREAD

**Issue by bryandh** [ovity/octotree#628] opened 2019-02-18 09:53 UTC
### Description
Won't display repo's contents, will continue to ask for an access token, which doesn't resolve the problem after entering it. This seems to only happen for branches with a forward-slash `/` in their names. As far as I can see, this issue is occurring since version 2.5.2. The issue does not occur on version 2.5.1.
Switching back to a branch without a forward-slash works and doesn't require me to enter my access token again.

See screenshot below of what is displayed for branches containing a forward-slash `/`.

### Environment (if bug)

* Octotree version: 2.5.2 to 2.5.5
* Browser & version: Firefox Developer Edition 66.0b5 & Google Chrome 72.0.3626.109
* OS & version: MacOS Mojave 10.14 Beta
* Screenshot, if any (drag an image here)
<img width="232" alt="screenshot 2019-02-18 at 10 46 44" src="https://user-images.githubusercontent.com/11500592/52942196-d2575700-336a-11e9-8dfe-51d51800831b.png">
* Console error log below this line
Not getting any console errors.

**Comment by hanssens** [comment] 2019-02-18 09:56
> This seems to only happen for branches with a forward-slash `/` in their names.

Nice find @bryandh. Encounter the same issue on Octotree v2.5.5, where my branches are named for example `fixes/xxx` and `releases/vnext` etc. Wasn't a problem in earlier versions.

**Comment by nphi1212** [comment] 2019-03-23 12:55
Hi @bryandh ,

I tried to fix the issue but I couldn't reproduce the bug. Could you help me reproduce it ? It seems I'm missing something. I'm using the latest version 2.5.6 

![Screen Shot 2019-03-23 at 7 54 38 PM](https://user-images.githubusercontent.com/8633840/54866381-9d915200-4da5-11e9-876f-f02d9c368bd9.png)

**Comment by hanssens** [comment] 2019-03-23 13:29
@nphi1212 I believe this is already fixed with PR #626, which is merged in v2.5.6, right?

**Comment by buunguyen** [comment] 2019-03-23 15:44
Doesn't hurt to try the latest version :)

**Comment by nphi1212** [comment] 2019-03-25 02:45
@hanssens Could you try to reproduce the issue in the latest version and confirm the issue fixed so we can close this issue?

Thanks in advance.

**Comment by bryandh** [comment] 2019-03-25 08:33
Just tested 2.5.6, looks like it has been fixed! 👍

**Comment by hanssens** [comment] 2019-03-25 08:34
Agreed, same here.

**Comment by buunguyen** [comment] 2019-03-26 06:30
Great, thanks for the update.

**Closed by buunguyen** 2019-03-26 06:30 UTC
