### ISSUE TITLE
Unable To Pin Sidebar

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#1006] opened 2020-09-17 15:44 UTC
### Description
Since updating the version `6.0.0`, and even after refreshing browser / opening a new tab, i am unable to pin the sidebar after clicking on the **pin** icon.

I am only able view the sidebar temporarily when i hover the cursor over the Octotree side-tab label.

### Environment (if bug)

* Octotree version: `6.0.0`
* Browser & version: `85.0.4183.102`
* OS & version: `10.15.6`
* Console error log below this line: `No console errors observed`

* Screenshot: `see GIF below`

![Octotree](https://user-images.githubusercontent.com/7581546/93493880-4883bd00-f904-11ea-97ab-9a97fa724108.gif)

**Comment by buunguyen** [comment] 2020-09-17 15:54
This is strange. Can you check if you don't happen to have multiple copies of Octotree by accident (I suppose not unless you build one from source, but just in case)? If not, please re-install Octotree to see if it still happens.

**Comment by Sayvai** [comment] 2020-09-17 16:03
Ok, so i had to uninstall and reinstall the extension, and it seems to be working ok now 😅 

For general information, I generally have a few tabs open on the same repo, but different areas of the repo (e.g, one tab for main repo page, another tab for individual pull requests, etc).

All good now, and keep up the great work 👍

**Comment by robyy** [comment] 2020-09-17 16:05
uninstall and reinstall resolved the same issue.

**Comment by buunguyen** [comment] 2020-09-17 18:11
Thanks for confirming @Sayvai and @robyy. I guess the problem is some other tabs still have the old version of Octotree. Gonna leave this issue open for a while to benefit those experiencing the same problem.

**Comment by ggascoigne** [comment] 2020-09-17 20:09
Sadly I've got the same problem.  I uninstalled octotree, then re-installed it, and restarted chrome. 

I've got different behavior on various pages. On some, the octotree pane simply doesn't show up, on others it will show up but won't allow me to pin it in place.  I've not seen a pattern to this.

On my GHE page it actually seem to be working correctly and is both visible and pinning in place.

**Comment by Sayvai** [comment] 2020-09-17 20:29
@buunguyen Hmm. I just navigated back to the same repo i had the original issue with, and the sidebar is no longer pinned, even thought i thought i remedied the issue [earlier](https://github.com/ovity/octotree/issues/1006#issuecomment-694333720) by reinstalling the [extension](https://www.octotree.io/download). 

When i tried to re-pin the sidebar again, i am no longer able to pin the sidebar, reproducing the same behaviour as seen in the original GIF screenshot on this issue.

It appears that the pinning mechanism is unstable.

Any ideas 🤔

**Comment by buunguyen** [comment] 2020-09-17 20:41
Can you go to chrome://extensions, click background page link in the Octotree extension. Then check the value of "octotree.sidebar_pinned" in chrome.storage.sync? I recommend [this extension](https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb?hl=en) to easily see storage values. Please double check that the value toggles between `true` and `false` as you pin/unpin. If it doesn't change value, please check if there's any error in the console. Thank you.

**Comment by ggascoigne** [comment] 2020-09-17 20:56
Well I'm not sure what the "background page link" is, but I can find the local storage in chrome when I'm looking at github.

octotree.sidebar_pinned was true even though the panel wasn't being displayed, it did not change when I toggled it.  Deleting that value and toggling the setting didn't cause it to suddenly show up.

interestingly, toggling the theme works fine and I can see the change in both octotree and the local storage.

**Comment by Sayvai** [comment] 2020-09-17 20:59
@buunguyen So I opened restarted Chrome again, navigated to GitHub repo, opened DevTools, and display the current Local Storage values (via Chrome's native Applications tab section). `octotree.sidebar_pinned` key is missing initially.

You can see on the attached GIF, from my first Octotree interaction, i change the theme successfully, where you can see the Local Storage value for the key `octotree.theme` change.

However, for the next interaction, attempting to pin the sidebar. The key `octotree.sidebar_pinned` was not even created upon clicking the pin icon. No console errors either. 🤔 

![2020-09-17 21 51 06](https://user-images.githubusercontent.com/7581546/93527478-d7a6ca00-f930-11ea-9ef7-36a9abb39d1f.gif)

**Comment by buunguyen** [comment] 2020-09-17 21:11
Thanks @Sayvai. First, I removed the image as it showed your token. 

Now, you have to check the background page of the extension because everything except from themes are stored in chrome storage, not local storage. So you need to go to chrome://extensions, find Octotree, click "background page". Then use the Storage Area Explorer extension to check value of octotree.sidebar_pinned. Please let me know what you find out.

Thanks for your support and my apologies about the bug.

**Comment by ggascoigne** [comment] 2020-09-17 21:15
Ah, you need to be in developer mode to see the background page option.

**Comment by ggascoigne** [comment] 2020-09-17 21:18
looking in chrome.storage.sync I see octotree.sidebar_pinned = true, and toggling it has no effect.  Interestingly the theme isn't stored here.

**Comment by Sayvai** [comment] 2020-09-17 21:18
@buunguyen Ok, so i tried that, and i don't see any kets under local, and session storage. 🤔 

@ggascoigne Annotated screenshot shows you where to find the link in developer mode (switch in top-right corner of extensions page. 

![Screenshot 2020-09-17 at 22 13 06](https://user-images.githubusercontent.com/7581546/93529267-86e4a080-f933-11ea-9801-9b333000b119.png)

Thanks for removing my earlier GIF by the way.

**Comment by buunguyen** [comment] 2020-09-17 21:21
Please install this extension: https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb?hl=en (you can delete it later, only need to view chrome storage)

In the background page, go to Storage Explorer, and look under chrome.sync.storage. Please see attached the screenshot from my computer.

<img width="579" alt="Screen Shot 2020-09-17 at 2 20 34 PM" src="https://user-images.githubusercontent.com/406631/93529565-f9805c80-f8f0-11ea-8ff1-9d552c5ad876.png">

**Comment by Sayvai** [comment] 2020-09-17 21:27
@buunguyen Ok, i installed the recommended extension for now. I do have the `octotree.sidebar_pinned` set to `true`... 🤔 

![Screenshot 2020-09-17 at 22 23 56](https://user-images.githubusercontent.com/7581546/93530102-eb542f80-f934-11ea-85b2-b59b26154b70.png)

**Comment by buunguyen** [comment] 2020-09-17 21:29
@Sayvai thanks. When you toggle, does it change value? And as of now, when the value is true, the sidebar is not pinned?

**Comment by Sayvai** [comment] 2020-09-17 21:29
> @Sayvai thanks. When you toggle, does it change value? And as of now, when the value is true, the sidebar is not pinned?

I just tried that, and the value doesn't change when i click on the pin icon.

**Comment by ggascoigne** [comment] 2020-09-17 21:30
I'm in the exact same boat as @Sayvai , clicking the pin button does not change the value in storage, and it is set to true and the sidebar is not pinned.

**Comment by buunguyen** [comment] 2020-09-17 23:34
@Sayvai @ggascoigne if possible, I'd like to you help run a debug version of Octotree which shows detailed logs of pin state change in the console. Hopefully I will be able debug the problem once seeing the log. If you're okay with that, please send me an email at support@octotree.io so I can share you the copy. Thanks for your support.

**Comment by BIAOXYZ** [comment] 2020-09-18 05:24
Met the same issue with @Sayvai and @ggascoigne .

**Comment by ghprod** [comment] 2020-09-18 07:55
:+1: 

Same issue with Chrome + Ubuntu

**Comment by buunguyen** [comment] 2020-09-18 20:15
Please try version 6.0.1 and let me know if the issue persists. Thanks.

**Comment by Sayvai** [comment] 2020-09-18 20:23
@buunguyen it's working so far on version `6.0.1`.

I can toggle the sidebar between pinned and unpinned state, even after restarting my browser and opening multiple tabs on the same repo 🤞

**Comment by buunguyen** [comment] 2020-09-18 20:32
Glad to hear. I couldn't reproduce the issue but I think it had something to do with Chrome storage synchronization (based on the info you provided via email, thank you!). I made a change so that pinning works even if Chrome sync acts crazy for whatever reason, instead of assuming it always works the way it's supposed to.

**Comment by buunguyen** [comment] 2020-09-22 18:19
I suppose 6.0.1 fixed this for everyone, closing this ticket now. Thanks @Sayvai and @ggascoigne for helping me troubleshoot this issue.

**Closed by buunguyen** 2020-09-22 18:19 UTC
