### ISSUE TITLE
Pages infinitely loading when "multi-tab" setting is enabled

### ISSUE THREAD

**Issue by neel-gandhi** [ovity/octotree#1124] opened 2022-03-17 04:06 UTC
### Description
All pages on any of the Github repositories keep reloading continuously if "Multi-tab" setting is enabled.
Seems to be very similar issue to https://github.com/ovity/octotree/issues/987

I came across solution to disable "multi-tab" to make it work from [this comment](https://github.com/ovity/octotree/issues/987#issuecomment-659720558).

### Environment (if bug)

* Octotree version: 7.4.0
* Browser & version: Chrome 99.0.4844.74
* OS & version: macOS Monterey v12.3
* Screenshot, if any (drag an image here): Image is from PR #987 - I am seeing exact same behavior, hence using that screenshot.
![image](https://user-images.githubusercontent.com/9889717/158735055-bd28550c-6f68-4f39-93e2-a7cc6535cb40.png)

* Console error log below this line

**Comment by danhgit** [comment] 2022-03-17 04:26
@neel-gandhi thanks a lot for reporting and digging out the cause. Indeed, multi-tab causes the issue. I just released a hot fix to temporarily remove this feature while we're working to address the root cause.

BTW, this issue was just reported a bit earlier https://github.com/ovity/octotree/issues/1123. I'm gonna close this so that we only track a single issue.

**Closed by danhgit** 2022-03-17 04:26 UTC
