### ISSUE TITLE
submodule link in GHE

### ISSUE THREAD

**Issue by IMOKURI** [ovity/octotree#720] opened 2019-05-15 06:46 UTC
### Description
Submodule link does not work for GitHub Enterprise.

### Environment (if bug)

* Octotree version: 1.0.7
* Browser & version: Chrome 74.0.3729.157
* OS & version: Windows 10 1709 
* Screenshot, if any (drag an image here)

![sub-repo](https://user-images.githubusercontent.com/1638500/57754016-7d886a00-7728-11e9-95b0-e750e1805b9e.gif)

* Console error log below this line

**Comment by nphi** [comment] 2019-05-19 13:46
Hmm. It's weird. I will investigate in the issue ASAP.

**Comment by IMOKURI** [comment] 2019-05-19 23:50
Our GHE url is not end with github.com. This may be help you for this issue?

**Comment by buunguyen** [comment] 2020-09-18 05:14
Sorry for taking long. Gonna close now as it's been a while. If it still occurs, please help suggest the cause.

**Comment by IMOKURI** [comment] 2020-09-18 06:18
This issue is still occered.
I use version 6.0.0.

Our GHE url does not end with `github.com`.
So I think following code may be failing to parse out GHE url.

https://github.com/ovity/octotree/blob/aa532ae2b71ce6eb4ad29fcfede442b7151046ec/src/adapters/adapter.js#L118-L127

I'm not good with javascript, so I'm not sure how to fix.

**Comment by buunguyen** [comment] 2020-09-18 06:26
What is the submodule URL? What is the one that Octotree returns? Feel free to replace sensitive characters, just need to know the structure.

**Comment by IMOKURI** [comment] 2020-09-18 06:36
This is submodule URL.

![image](https://user-images.githubusercontent.com/1638500/93564330-76c8d180-f9c4-11ea-882e-6ca5c95b6053.png)

**Comment by danhgit** [comment] 2022-05-05 02:21
This should have been fixed in 7.5.0. Please check and let us know.

**Closed by danhgit** 2022-05-05 02:21 UTC
Labels: ghe
