### ISSUE TITLE
sidebar opens on every single github page without any interaction

### ISSUE THREAD

**Issue by pdeva** [ovity/octotree#669] opened 2019-04-15 16:34 UTC
### Description
Since the latest update, the octotree sidebar pops up automatically on every single github page i open without hovering/clicking on the octotree button. it is extremely annyoying since i have to then close it every time.

### Environment (if bug)

* Octotree version: 3.0.1
* Browser & version: Chrome 73
* OS & version: windows 10

**Comment by nphi** [comment] 2019-04-15 16:38
Hi @pdeva ,

Could you check if it's similar to this reported issue https://github.com/ovity/octotree/issues/663 ? If it is, the bug would be fixed ASAP.

Thanks for reporting the issue.

**Comment by pdeva** [comment] 2019-04-15 16:42
yes it does seem a duplicate of it

**Comment by oganm** [comment] 2019-04-16 01:05
Is this truly a duplicate? I experience this in non-private repos as well, for instance this very repo

**Comment by pdeva** [comment] 2019-04-16 01:06
same

**Comment by buunguyen** [comment] 2019-04-16 01:20
Can anyone have the steps to reproduce? Would be very helpful.

**Comment by oganm** [comment] 2019-04-16 01:39
Refresh this page, click anywhere on the screen. Octotree pops up

**Comment by buunguyen** [comment] 2019-04-16 02:25
Can you check that you are indeed running the latest version (3.0.2)?

**Comment by Justineo** [comment] 2019-04-16 02:48
I can confirm I'm running `v3.0.2` and it still happens.

**Comment by buunguyen** [comment] 2019-04-16 03:03
Can you post more info, e.g. OS, browser, version etc. and how to reliably replicate the bug? We have a hard time as none of us could reproduce it. Thanks!

**Comment by Justineo** [comment] 2019-04-16 03:26
macOS Mojave 10.14
Chrome v73.0.3683.103

Reproduction steps:

1. Go to any repository
2. * Click anywhere on the page
    * Or, switch to another tab and switch back

**Comment by oganm** [comment] 2019-04-16 04:31
Mine is also 3.02

**Comment by nphi** [comment] 2019-04-16 05:47
I have spent an hour trying to reproduce the bug but with no success. Could someone help me create a video or gif ? Really appreciate it.

**Comment by Justineo** [comment] 2019-04-16 05:55
![octotree](https://user-images.githubusercontent.com/1726061/56185133-36d32180-604f-11e9-942d-8152baed2e50.gif)

**Comment by oganm** [comment] 2019-04-16 06:00
I was also able to reproduce it after disabling all other browser extensitons

**Comment by eemeli** [comment] 2019-04-16 09:34
I've now disabled Octotree because of this issue; the constantly appearing and then disappearing sidebar is too distracting.

**Comment by CollinChaffin** [comment] 2019-04-16 17:23
Same here as of the free/pro split the free version is totally unusable.  I have experienced both this issue and then when the pane does actually appear properly, it now only as of this version for the first time over 75% of the time does not shift content and due to the overlap makes the entire page unreadable.

**Comment by pdeva** [comment] 2019-04-16 17:25
i have disabled it too now. makes using github impossible with it on

**Comment by nphi** [comment] 2019-04-16 18:10
I have created an PR addressing the clicking issue. I'm wondering if anyone encounters the issue without clicking or switching tabs. If yes, could you do me a favor by creating a gif so that I could resolve the bug as soon as possible so that you guys could enjoy the Octotree again. Many thanks in advance.

**Comment by oganm** [comment] 2019-04-16 22:14
This is very sporadic so I am having a hard time recording anything but occasionally octotree will reveal itself when I simply move my inside the page or on page load

**Comment by tabatkins** [comment] 2019-04-17 00:06
I'm getting this (on v3.0.2, running ChromeOS 74). Every time a GitHub page loads (from following a link, or from refreshing the page), the octotree sidebar pops open as soon as it loads up. It goes away when I click somewhere else in the page. Unlike other people, it doesn't wait for me to move my mouse or click somewhere, it opens automatically as soon as it can, even if I refresh the page and then don't touch anything.

**Comment by nphi** [comment] 2019-04-17 02:19
@tabatkins

Could you do me a favor by taking a gif? Also giving as much information as possible, That would help a lot for debugging. 

Thanks for reporting the issue

**Comment by buunguyen** [comment] 2019-04-17 02:20
@CollinChaffin if you pin the sidebar, then the content will shift. If not (we call it float mode), it won't shift. The idea is floating sidebar is very temporary, you go there to find a pick, click it then immediately focus on the content (the sidebar will automatically hide after a few short secs or immediately if you click anywhere in the page). Maybe we should reduce the duration of the sidebar automatically closing?

**Comment by buunguyen** [comment] 2019-04-17 02:25
Everyone, we've just release 3.0.4 with a fix. Please give it a try. Because there are multiple issues reported in this thread and not everything we could reproduce, I'm not sure if the fix addresses all issues. If anyone still having any problem, we really appreciate you open a new bug with more info to help us reproduce the issue, like: OS, browser, how many monitors you use and which monitor (left or right) Octotree is located, detailed steps to reproduce (video/gif would be great). Keep in mind we have tried but couldn't reproduce all reported issues; if we could, we would have fixed the problem very quickly. Therefore, your help is highly appreciated.

**Closed by buunguyen** 2019-04-17 02:25 UTC

**Comment by Justineo** [comment] 2019-04-17 02:33
Thanks! I can confirm the latest version works as expected now. No more automatical opening up on clicks or tab switches. 👍

**Comment by buunguyen** [comment] 2019-04-17 02:37
Awesome, great to hear @Justineo!

**Comment by tabatkins** [comment] 2019-04-17 03:47
Confirmed, 3.0.4 fixes the issue for me. Thanks so much!
