### ISSUE TITLE
Disable "Open sidebar on hover" doesnt work

### ISSUE THREAD

**Issue by ro0NL** [ovity/octotree#659] opened 2019-04-15 07:46 UTC
Version
3.0.1

Chrome  73.0.3683.103 

I've disabled the option "Open sidebar on hover", yet the sidebar stil seems to open when i hover above/below the "Octotree handle"

![image](https://user-images.githubusercontent.com/1047696/56115302-6147b080-5f63-11e9-9cea-4ee21fd9318f.png)

**Comment by andywillis** [comment] 2019-04-15 09:49
As an aside, I really like this tool, but, fwiw, the old UI for opening/closing the tool was much more useful and intuitive. "Click to open" is better than "click/hover to open, then pin to keep open", and "click to close" is better than "unpin and to wait for the sidebar to close".

**Comment by nphi** [comment] 2019-04-15 09:59
Hi, @ro0NL !

Somehow I couldn't reproduce the bug with the normal environment. It seems I'm missing something. Do you use other plugins ? It would be helpful if you can take a screenshot with console dev inspecting the DOM tree of the Octotree handle.

Thanks for reporting the issue.

**Comment by YongYuH** [comment] 2019-04-15 10:08
I use `Octotree` along with `ZenHub for GitHub` at the same time and encounter the same issue.

**Comment by ro0NL** [comment] 2019-04-15 10:15
@nphi i can confirm it's caused by a browser extension; in my case "[A Pixel Ruler For Web Developers](https://chrome.google.com/webstore/detail/designers-ruler/mlbnpnlmfngmlcmkhjpbfokdphfehhjj)" :joy:

**Comment by nphi** [comment] 2019-04-15 10:21
I can reproduce it now. :) I will make a PR to fix the issue ASAP.

**Comment by buunguyen** [comment] 2019-04-16 02:15
This should have been fixed in the latest release. If it still occurs, please let us know. Thanks for reporting the issue!

**Closed by buunguyen** 2019-04-16 02:15 UTC
