### ISSUE TITLE
Infinite page loading resulting in failed API requests 

### ISSUE THREAD

**Issue by medmin** [ovity/octotree#1123] opened 2022-03-17 03:46 UTC
### Description
If this is a bug, provide as much information as you can to help reproduce the issue.

### Environment (if bug)

* Octotree version:  7.4.0
* Browser & version: chrome 7.4.0
* OS & version: windows 10
* Screenshot, if any (drag an image here)
* Console error log below this line

**Comment by rqx110** [comment] 2022-03-17 03:55
face the same problem this morning

**Comment by danhgit** [comment] 2022-03-17 04:24
Hi, thanks for reporting. Please go to Octotree settings screen and disable the multi-tab feature. Looks like GitHub has made some change that conflicts with this feature. Because this is a serious bug, I just released a hot fix that temporarily removes multi-tab so that those who miss this comment can still use Octotree. We'll add support back after fixing the issue.

**Comment by kevnm67** [comment] 2022-03-18 16:44
+1 

https://user-images.githubusercontent.com/2734154/159046042-ad0faf7c-0ef3-4413-a281-8a0ab368696d.mp4


Here's a screen recording to demonstrate the issue.

**Comment by kevcube** [comment] 2022-03-20 22:00
@danhgit please release this hotfix to App Store version.

**Comment by alle** [comment] 2022-03-22 14:10
> ### Description
> If this is a bug, provide as much information as you can to help reproduce the issue.
> 
> ### Environment (if bug)
> * Octotree version:  7.4.0
> * Browser & version: chrome 7.4.0
> * OS & version: windows 10
> * Screenshot, if any (drag an image here)
> * Console error log below this line

Same behavior is reproducible in Safari, too.

**Comment by danhgit** [comment] 2022-03-23 16:58
We fixed the multi-tab issue and released with 7.4.3. 

@alle @kevcube the Safari version just goes through Apple's moderation and is available now. Moderation is usually the hold-up when coming to App Store...

**Closed by danhgit** 2022-03-23 16:58 UTC
