### ISSUE TITLE
Dark Themes - Colourise Pull Request List Icons

### ISSUE THREAD

**Issue by Sayvai** [ovity/octotree#959] opened 2020-06-03 07:47 UTC
### Description
When viewing the Pull Requests GitHub page (and PR lists page), the mini Failed, Pass, and even the Merge icons are de-colourised for each Pull Request listed when using any of the Dark themes (eg, _Monokai_). 

It makes it hard to distinguish between Pull Requests which have failed, or passed the automated build checks (eg, Jenkins tests) integrated into the repositories (if applicable).

A suggestion is to at least maintain the same colour to the icons that is visible when no colour theme is set (eg, red for Failed, Green for Passed, and also Green for the Merge icon to the left of the Pull Request title)

### Environment (if bug)

* **Octotree version**: 5.0.0
* **Browser & version**: 83.0.4103.61
* **OS & version**: OS X 10.15.5 (Catalina)
* **Screenshot**:
![Octotree-Monokai-Color-Theme](https://user-images.githubusercontent.com/7581546/83609014-90f5b580-a575-11ea-8567-c358998ac395.png)

![Screenshot 2020-06-03 at 15 07 38](https://user-images.githubusercontent.com/7581546/83647388-bce05d80-a5ac-11ea-8f02-8dba15a7f8b8.png)

* **Console error log below this line**: N/A

**Comment by buunguyen** [comment] 2020-06-03 18:22
Fixed in 5.0

**Comment by buunguyen** [comment] 2020-06-03 19:03
Sorry I was commenting on the wrong issue. This is not fixed.

**Comment by JoepKockelkorn** [comment] 2020-06-04 09:06
I can confirm this bug on version 5.0.0. It seems the css selectors for the themes are too generic, or are missing modifiers for the 'open' or 'approved' state of icons. For the Railscasts theme these are some fixes I applied myself using the Stylus extension for the 'open' PR's in the PR overview and the approval icons in a PR:
```css
html.octotree-theme-railscasts svg.open {
  fill: rgb(108, 198, 68);
}

html.octotree-theme-railscasts .TimelineItem-badge.bg-green {
  background-color: rgb(51, 119, 51) !important;
}
```

**Comment by buunguyen** [comment] 2020-06-04 18:15
We use the theme files from https://github.com/StylishThemes/GitHub-Dark. We'll need to figure out if the problem is caused by the source theme files or only an problem when applied in Octotree. If the former, best to open an issue in GitHub Dark instead.

**Comment by AlecRust** [comment] 2020-06-29 12:35
Apparently these are green in GitHub-Dark:

https://github.com/StylishThemes/GitHub-Dark/issues/1117#issuecomment-638176813

How recent is the GitHub-Dark version in Octotree, does it just need to be updated?

**Comment by buunguyen** [comment] 2020-07-01 20:24
Fixed in 5.2.1

**Closed by buunguyen** 2020-07-01 20:24 UTC

**Comment by Sayvai** [comment] 2020-07-02 09:47
@buunguyen i've just verified the colours are restored correctly now. Many thanks for your work on the fix 👍

**Comment by buunguyen** [comment] 2020-07-02 18:35
@Sayvai thanks for confirming, glad to hear.
