### ISSUE TITLE
Not compatible with GitHub Wide plugin

### ISSUE THREAD

**Issue by DoCode** [ovity/octotree#497] opened 2018-03-10 13:54 UTC
### Description
With [this](https://github.com/xthexder/wide-github) extension enabled the side menu to overlap the content when the window is very widescreen.

### Environment

* Octotree version: 2.4.4
* Browser & version: Google Chrome v65.0.3325.125 (Official Build) beta (64-bit)
* OS & version: Windows 10 Pro 1709 x64

![octotree-overlap-content](https://user-images.githubusercontent.com/1489133/37243018-ed638684-2472-11e8-9c35-a643c368a5a4.gif)

**Comment by Yantrio** [comment] 2018-03-19 10:05
I am also seeing this in chrome 65 on osx.

**Comment by vlascik** [comment] 2018-05-18 10:14
Had a similar problem, this is perhaps better solved by editing your wide github userstyle and adding style like this:
```
.container-lg {
	max-width: inherit !important;
}
```
The problem is, that the top container doesn't stretch to whole width, which means on line 952 of octotree
```
      var autoMarginLeft = ($(document).width() - $containers.width()) / 2;
      var shouldPushLeft = sidebarVisible && autoMarginLeft <= sidebarWidth + SPACING;
```
based on the top bar's width, automargin is going to be computed as already wider as content (and octotree will then decide that it doesn't need to push the content from the left). Adding style above unsets the max-width set by github's css by default, thus stretching the top bar to full width, octotree then works as expected.

**Comment by MiracleBlue** [comment] 2018-11-05 06:10
@vlascik 	It works!  Thank you so much!  I tried so many things in my userstyles, eventually settling on just setting a fixed margin-left which wasn't all that good either.  Your suggestion works perfectly though!

**Comment by aspiers** [comment] 2019-04-14 12:13
That PR was closed with no explanation, so I asked for one.

**Comment by buunguyen** [comment] 2019-04-17 02:50
Is it still a problem with the latest UI change in Octotree? Can anyone confirm?

**Comment by vlascik** [comment] 2019-04-17 03:07
@buunguyen yes, it is.

**Comment by CollinChaffin** [comment] 2019-04-18 00:39
I can confirm when I also said this in #657 that not only is this happening in the GH wide PLUGIN, but in my case also anyone running Tampermonkey on Chrome with the equivalent GH wide USERSCRIPT (which does the same thing).

The issue is that the wide fires timing-wise before the Octotree or at the same time, and Octotree must be reading the stale non-wide (non-altered) layout and simply creates it's element overlapping without the shift.

What is odd, however, is that the version prior to the pro/free split that also came with the Octotree pane redesign actually DID work correctly the majority of the time which further strengthens the idea that it may be a change in the timing.

**Comment by CollinChaffin** [comment] 2019-04-18 00:45
I can also, however, confirm that per @vlascik suggestion above, that appending/altering the GH Wide userscript I'm using to break out this on it's own:

```
".container-lg {" +
"	max-width: inherit !important;" +
"}" +
```

Does in fact completely resolve the Octotree pane overlap issue 100% of the time for me.  Thanks @vlascik!

**Comment by CollinChaffin** [comment] 2019-05-18 03:58
Update: My last comment was not entirely accurate.  After more testing, I can confirm that at least while using the Github Wide Userscripts, the overlap issue still occurs even as of the current build of v3.0.7.  It is very annoying and since I don't recall it happening prior to this latest redesign, why that expansion behavior of old cannot simply be carried forward?

**Comment by CollinChaffin** [comment] 2019-05-19 10:37
Fixed.  I just submitted a PR that I have been running all night with 100% success due to changes I made not only in the CSS, but the overall preprocessor loading directives to ensure Octotree always loads first and the GH wide then recognizes the smaller usable canvas left over if the Octotree pane is pinned.

https://github.com/xthexder/wide-github/pull/45

Let's leave this issue open until the PR is merged and the masses confirm it as well.

**Comment by nphi** [comment] 2019-05-19 13:41
@CollinChaffin, I really appreciate your effort and enthusiasm. Many thanks for your support.

**Comment by buunguyen** [comment] 2019-08-15 17:36
@CollinChaffin I see the PR was closed. Can anyone confirm if you still have the problem?

**Comment by buunguyen** [comment] 2020-06-03 18:26
We just release 5.0 with update to layout mechanism. Can someone confirm it fix this issue?

**Comment by nobe0716** [comment] 2020-06-04 02:41
Hello, I tested it and it seems to be resolved.
Octotree does not overlap with pinned side bar.

![image](https://user-images.githubusercontent.com/5964919/83708789-0df95b80-a658-11ea-82fa-ed2acfb4582f.png)
![image](https://user-images.githubusercontent.com/5964919/83708805-181b5a00-a658-11ea-8835-06e67d35f1fb.png)

### Environment
- chrome (maybe latest version)
- github-wide css: latest release from https://github.com/mdo/github-wide

**Comment by buunguyen** [comment] 2020-06-04 02:54
Great to hear! Thanks for letting us know. Gonna close this issue now.

**Closed by buunguyen** 2020-06-04 02:54 UTC
Labels: help wanted
