### ISSUE TITLE
DB Connection error when using "Login with GitHub" method for login

### ISSUE THREAD

**Issue by jordangarrison** [ovity/octotree#1060] opened 2021-03-15 22:20 UTC
### Description
Attempted to clear cache and re-login to the extension. The problem persists before and after.

The issue shows the following error:

```
no pg_hba.conf entry for host "[aws-server-ip]", user "[db-user-name]", database "[database-name]", SSL off
```
Is it possible the API server is not permitted to connect to the database?

### Environment (if bug)

* Octotree version: v6.3.0
* Browser & version: Brave Version 1.21.76 Chromium: 89.0.4389.86 (Official Build) (x86_64)
* OS & version: MacOS Big Sur 11.2.3
* Screenshot, if any (drag an image here)
![2021 03 15-17 11 16](https://user-images.githubusercontent.com/22905777/111228135-b3f7d000-85b1-11eb-81b5-14596c26feb7.png)
* Console error log below this line - Unable to grab as the error occurs in the popup window

**Comment by jdreesen** [comment] 2021-03-15 22:28
Duplicate of #1059

**Comment by jordangarrison** [comment] 2021-03-15 22:38
Ah, didn't see that one, looks like they beat me to it.

**Comment by jordangarrison** [comment] 2021-03-15 22:49
This is resolved on my end now.

**Comment by jdreesen** [comment] 2021-03-15 22:54
Works for me again, too.

**Comment by danhgit** [comment] 2021-03-15 22:59
Thanks for confirming, @jordangarrison and @jdreesen! I also changed the code to show generic error log instead. I'm closing this issue now.

**Closed by danhgit** 2021-03-15 22:59 UTC
