### ISSUE TITLE
Expecting a port to Microsoft Edge

### ISSUE THREAD

**Issue by lizy14** [ovity/octotree#480] opened 2018-01-16 05:45 UTC

**Comment by buunguyen** [comment] 2018-01-27 05:18
Seems reasonable as Edge extensions are Chrome-compatible. I don't develop on Windows and wouldn't have time for this anyway. Anyone wants to take on?

**Comment by Jack-Q** [comment] 2018-01-31 15:30
Hi @buunguyen, I have made some attempts to port is to Edge. 
Currently, it basically works well in Edge, while with the following features are broken:

* file-specific icons
* expanding animation of js-tree

Here is a preview of a GitHub page with Octotree in Edge:
![image](https://user-images.githubusercontent.com/9014072/35631359-ab4557de-06de-11e8-8f4a-a2484cc5997b.png)

**Comment by Jack-Q** [comment] 2018-04-19 08:49
Update:
Currently, the animation of js-tree works fine in the latest version of Edge. And the file-specific icon is still blocked due to the failure of icon font loading (Caused by an issue of Edge [https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11320212/]()).

**Comment by NitroAMD** [comment] 2018-05-04 06:45
@Jack-Q - Thank you for your efforts here. The latest Windows 10 1803 update should fixed the Edge issues. I appreciate your work here and hope to see Octotree for Edge soon. :-)

**Comment by lizy14** [comment] 2018-05-30 04:18
May I ask the progress please? When can I expect a binary release to sideload, and further, listing in Microsoft Store?

**Comment by buunguyen** [comment] 2018-05-30 04:34
There's a PR here: https://github.com/buunguyen/octotree/pull/488.
I'm busy right now and I can't install VM/Edge and test it out. If anyone can test the Edge PR locally and confirm it works then I can merge it.

**Comment by NitroAMD** [comment] 2018-06-04 14:17
I tried to use PR #488 but it don't work for me at all. Any thoughts?
https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/adding-and-removing-extensions#adding-an-extension

![image](https://user-images.githubusercontent.com/1763966/40922551-c310ef6e-6812-11e8-8789-1f587f6ff7be.png)

**Comment by Jack-Q** [comment] 2018-06-04 16:50
Hi @NitroAMD, this project needs to be built before sideload. You can use `gulp edge` command to build it against Edge (don't forget `npm install`). Then, you can sideload the folder `tmp\edge\Extension`. 

After building, the version number in the manifest will be replaced by the real one and shown in the extension info page. Here is a screenshot showing that.
![image](https://user-images.githubusercontent.com/9014072/40930434-42a2da7a-685a-11e8-851b-a2d709e8211b.png)

**Comment by NitroAMD** [comment] 2018-06-05 15:23
@Jack-Q Thank you for the hint and after some gulp issues, I was able to build it, but I still face the file-specific icons problems.

![image](https://user-images.githubusercontent.com/1763966/40985826-2e9e8840-68e5-11e8-82b1-a7e8e60500af.png)

**Comment by lizy14** [comment] 2018-06-07 12:35
After I build and sideload it, navigating to a github repo, i see 14 lines of error `SCRIPT16389: Unspecified error. polyfill (1,2)` in F12 console, where `polyfill` points to a minified js file under `ms-browser-extension://octotree/ms-browser-extension:/`
<p></p>
I'm with OS build 17134.48. I don't even know how to get started with this.
<p></p>
Maybe related, the first time i run `gulp edge` i get `'lib:ondemand' errored`: `Error: ENOENT: no such file or directory, open 'C:\_O\octotree\tmp\ondemand.js'`; then i do nothing and run `gulp edge` again, it passes without errors.

**Comment by lizy14** [comment] 2019-05-03 17:31
In the news, [Microsoft moves from EdgeHTML to Chromium](https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/). As far as I see, this issue can be closed. 

I confirm that the latest version 3.0.7, installed from Chrome Web Store, works nice in the latest Chromium Edge dev (75.0.139.4).

**Comment by buunguyen** [comment] 2019-05-03 17:41
@lizy14 awesome! Thanks for letting us know. Closing the issue now.

**Closed by buunguyen** 2019-05-03 17:41 UTC
Labels: enhancement, help wanted

**Comment by vincentdchan** [comment] 2020-03-07 07:11
Chromium Edge is released, will this extension published to Microsoft Store?

**Comment by buunguyen** [comment] 2020-07-31 03:09
Done https://microsoftedge.microsoft.com/addons/detail/octotree/joagmknfcgpikbadjkaikmnhpjadihjg
