### ISSUE TITLE
Octotree Pro continuously refreshes Github edge pages 

### ISSUE THREAD

**Issue by yuchunc** [ovity/octotree#989] opened 2020-07-17 10:18 UTC
### Description
Octotree Pro keeps reloading Github page if I am on a edge page.
ie. https://github.com/ovity/octotree/blob/master/README.md

### Environment (if bug)

* Octotree version: 5.2.1
* Browser & version: Chrome 84.0.4147.89
* OS & version: macOS 10.15.5
* Console error log below this line
  * There is no console error log.

**Comment by jdreesen** [comment] 2020-07-17 11:53
Possible duplicate of #987

**Comment by buunguyen** [comment] 2020-07-17 18:02
Fixed in 5.4.0

**Closed by buunguyen** 2020-07-17 18:02 UTC
